version: "3.1"
services:
  mysql:
    image: mysql
    container_name: mysql
    env_file:
      - ./mysql/config/mysql.env
    ports:
      - 3306:3306
    volumes:
      - ./mysql/data_dir:/var/lib/mysql
      - ./mysql/init_scripts:/docker-entrypoint-initdb.d
    networks:
      - monitor

  grafana:
    depends_on:
      - mysql
    image: grafana/grafana
    container_name: grafana
    env_file:
      - ./grafana/config/grafana.env
    ports:
      - 3000:3000
    networks:
      - monitor
    links:
      - mysql:mysql
    volumes:
      - ./grafana/data_dir:/var/lib/grafana

  mosquitto:
    depends_on: 
      - mysql
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
      - 1883:1883
      - 9001:9001
    networks:
      - monitor 
    volumes:
#       - ./mosquitto/conf:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log 

  mqtt_listener:
    container_name: mqtt_listener
    depends_on: 
      - mosquitto
      - mysql
    build: ./mqtt_listener 
    ports:
      - 1884:1883
    networks:
      - monitor
    volumes:
      - ./mqtt_listener/logs:/logs

  data_generator:
    container_name: data_generator
    depends_on: 
      - mosquitto
      - mqtt_listener
    build: ./data_generator
    ports:
      - 1885:1883
    networks:
      - monitor

networks:
  monitor:
    driver: bridge
