version: "3.1"
services:
  mysql:
    image: mysql
    container_name: mysql
    env_file:
      - ./config/mysql.env
    ports:
      - 3306:3306
    volumes:
#      - ./mysql_data_dir:/var/lib/mysql
      - ./init_scripts:/docker-entrypoint-initdb.d
    networks:
      - enviro_net

  grafana:
    depends_on:
      - mysql
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    networks:
      - enviro_net
    links:
      - mysql:mysql
    volumes:
      - ./grafana_data_dir:/var/lib/grafana

networks:
  enviro_net:
    driver: bridge
