version: "3.1"
services:
  mysql:
    image: mysql
    container_name: mysql
    env_file:
      - ./config/mysql.env
    ports:
      - 3306:3306
    volumes:
      - ./mysql_data_dir:/var/lib/mysql
      - ./init_scripts:/docker-entrypoint-initdb.d
    networks:
      - enviro_net

  grafana:
    depends_on:
      - mysql
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    networks:
      - enviro_net
    links:
      - mysql:mysql
    volumes:
      - ./grafana_data_dir:/var/lib/grafana

  mosquitto:
    depends_on: 
      - mysql
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
      - 1883:1883
      - 9001:9001
    networks:
      - enviro_net 
    volumes:
#       - ./mosquitto/conf:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log 

  mqtt_listener:
    depends_on: 
      - mosquitto
    build: ./mqtt_listener 
    ports:
      - 1884:1883
    networks:
      - enviro_net

  mock_data_generator:
    depends_on: 
      - mosquitto
      - mqtt_listener
    build: ./mock_data_generator
    ports:
      - 1885:1883
    networks:
      - enviro_net

networks:
  enviro_net:
    driver: bridge
