#!/bash/bash

# initalise MySQL database
# Add this file to the container via the Dockerfile
# Add a volume 

set -e 
set -x

mysql_install_db

# Start the MySQL daemon in the background.
/usr/sbin/mysqld &
mysql_pid=$!

until mysqladmin ping >/dev/null 2>&1; do
  echo -n "."; sleep 0.2
done

# Permit root login without password outside container.
# Is this the right thing to do, I wonder?
mysql -e "GRANT ALL ON *.* TO root@'%' IDENTIFIED BY '' WITH GRANT OPTION"

# create the default database from the add'd file
mysql < schema.sql

# Shutdown the MySQL daemon
mysqladmin shutdown

# wait for it to exit
wait $mysql_pid

# create the tar file with the database as it currently stands
tar czvf default_mysql.tar.gz /var/lib/mysql

# the tar file contains the initalised state of the database 
